blueprint:
  name: Fenster/Tür offen bei Kälte Warnung
  description: Benachrichtigt wenn ein Fenster oder eine Tür länger als die konfigurierte Zeit bei niedrigen Außentemperaturen offen ist.
  domain: automation
  source_url: https://github.com/Nils3311/ha-fenster-kaelte-warnung-blueprint/blob/main/cold_window_alert_blueprint.yaml
  input:
    window_door_sensor:
      name: Fenster/Tür Sensor
      description: Der Sensor der überwacht werden soll
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class:
                - door
                - window
                - opening
    duration_minutes:
      name: Dauer (Minuten)
      description: Wie lange das Fenster/die Tür offen sein muss bevor eine Warnung gesendet wird
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "min"
          mode: slider
    temperature_threshold:
      name: Temperatur Schwelle
      description: Temperatur unter der die Warnung gesendet werden soll
      default: 15
      selector:
        number:
          min: -20
          max: 30
          unit_of_measurement: "°C"
          mode: slider
    weather_entity:
      name: Wetter Entity
      description: Wetter-Entity die für die Außentemperatur verwendet wird
      default: weather.forecast_home
      selector:
        entity:
          filter:
            - domain: weather
    enable_second_reminder:
      name: Zweite Erinnerung aktivieren
      description: Soll eine zweite Erinnerung gesendet werden, wenn das Fenster/die Tür immer noch offen ist?
      default: false
      selector:
        boolean:
    second_reminder_delay:
      name: Verzögerung für zweite Erinnerung (Minuten)
      description: Wie lange nach der ersten Erinnerung soll die zweite gesendet werden?
      default: 30
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: "min"
          mode: slider

mode: queued
max: 20

trigger:
  - platform: state
    entity_id: !input window_door_sensor
    to: "on"
    for:
      minutes: !input duration_minutes

condition:
  - condition: numeric_state
    entity_id: !input weather_entity
    attribute: temperature
    below: !input temperature_threshold

action:
  - variables:
      weather_entity: !input weather_entity
      duration_minutes: !input duration_minutes
      enable_second_reminder: !input enable_second_reminder
      second_reminder_delay: !input second_reminder_delay
      window_sensor: !input window_door_sensor
  - action: notify.notify
    data:
      message: >-
        {{ trigger.to_state.attributes.friendly_name | default(trigger.to_state.entity_id) }}
        ist seit über {{ duration_minutes }} Minuten offen,
        bei {{ state_attr(weather_entity, 'temperature') }}°C draußen.
        Denke daran es zu schließen.
  - if:
      - condition: template
        value_template: "{{ enable_second_reminder }}"
    then:
      - wait_for_trigger:
          - platform: state
            entity_id: !input window_door_sensor
            to: "off"
        timeout:
          minutes: "{{ second_reminder_delay }}"
      - if:
          - condition: template
            value_template: "{{ wait.trigger == none }}"
        then:
          - action: notify.notify
            data:
              message: >-
                ⚠️ ZWEITE ERINNERUNG: {{ state_attr(window_sensor, 'friendly_name') | default(window_sensor) }}
                ist immer noch offen (seit über {{ duration_minutes + second_reminder_delay }} Minuten),
                bei {{ state_attr(weather_entity, 'temperature') }}°C draußen.
                Bitte schließen!
